import * as fs from "fs";
import * as path from "path";
import type { AuditReport } from "./cli";

export async function saveReport(
  report: AuditReport,
  outputPath: string,
  asJson: boolean = false
): Promise<void> {
  const dir = path.dirname(outputPath);
  if (dir !== "." && dir !== "") {
    fs.mkdirSync(dir, { recursive: true });
  }

  const ext = path.extname(outputPath).toLowerCase();

  if (ext === ".json" || asJson) {
    fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
  } else {
    const md = reportToMarkdown(report);
    fs.writeFileSync(outputPath, md);
  }
}

function reportToMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  lines.push("# Web Performance Audit");
  lines.push("");
  lines.push("**URL:** " + report.url);
  lines.push("**Date:** " + new Date(report.timestamp).toLocaleString());
  lines.push("");
  lines.push("## Scores");
  lines.push("");

  for (const [cat, score] of Object.entries(report.scores)) {
    const filled = Math.floor(score / 5);
    const empty = 20 - filled;
    const bar = "\u2588".repeat(filled) + "\u2591".repeat(empty);
    const emoji = score >= 90 ? "\uD83D\uDFE2" : score >= 50 ? "\uD83D\uDFE1" : "\uD83D\uDD34";
    lines.push("- **" + cat + ":** " + emoji + " " + score + "/100 `" + bar + "`");
  }

  lines.push("");
  lines.push("## Core Web Vitals");
  lines.push("");

  const m = report.metrics;
  if (m.fcp !== undefined) lines.push("- **First Contentful Paint:** " + m.fcp + " ms");
  if (m.lcp !== undefined) lines.push("- **Largest Contentful Paint:** " + m.lcp + " ms");
  if (m.cls !== undefined) lines.push("- **Cumulative Layout Shift:** " + m.cls);
  if (m.tbt !== undefined) lines.push("- **Total Blocking Time:** " + m.tbt + " ms");
  if (m.si !== undefined) lines.push("- **Speed Index:** " + m.si + " ms");
  if (m.tti !== undefined) lines.push("- **Time to Interactive:** " + m.tti + " ms");
  if (m.ttfb !== undefined) lines.push("- **Time to First Byte:** " + m.ttfb + " ms");

  if (report.suggestions.length > 0) {
    lines.push("");
    lines.push("## Suggestions");
    lines.push("");
    for (const s of report.suggestions.slice(0, 15)) {
      lines.push("- [" + s.impact.toUpperCase() + "] **" + s.title + "** (" + s.category + ")");
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [webperf](https://github.com/sulthonzh/webperf)*");

  return lines.join("\n");
}
